/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DlibWrapper */

#ifndef _Included_DlibWrapper
#define _Included_DlibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DlibWrapper
 * Method:    detectFaces
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_DlibWrapper_detectFaces
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
